const region='europe-west2';
const message=document.querySelector('#message'),authCard=document.querySelector('#authCard'),learnerCard=document.querySelector('#learnerCard'),billingCard=document.querySelector('#billingCard'),billingStatus=document.querySelector('#billingStatus'),manageSubscription=document.querySelector('#manageSubscription'),supportCard=document.querySelector('#supportCard'),supportForm=document.querySelector('#supportForm'),supportStatus=document.querySelector('#supportStatus'),practiceCard=document.querySelector('#practiceCard'),questions=document.querySelector('#questions'),questionNav=document.querySelector('#questionNav'),progress=document.querySelector('#progress'),nextBatch=document.querySelector('#nextBatch');
const [{initializeApp},{getAuth,onAuthStateChanged,signInWithEmailAndPassword,signOut,sendPasswordResetEmail},{getFunctions,httpsCallable},{initializeAppCheck,ReCaptchaEnterpriseProvider}]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.7.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.7.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.7.0/firebase-functions.js'),import('https://www.gstatic.com/firebasejs/12.7.0/firebase-app-check.js')]);
const app=initializeApp(window.BRIGHTSUM_FIREBASE_CONFIG); initializeAppCheck(app,{provider:new ReCaptchaEnterpriseProvider(window.BRIGHTSUM_APP_CHECK_SITE_KEY),isTokenAutoRefreshEnabled:true}); const auth=getAuth(app),functions=getFunctions(app,region);
const call=name=>httpsCallable(functions,name); let learnerId='',batch=null;
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function speak(text){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text));}
function render(){questions.innerHTML='';questionNav.innerHTML=''; const completed=batch.completedQuestionIds?.length||0; progress.textContent=`${batch.year} · Batch ${(batch.batchIndex||0)+1} · ${completed} of ${batch.batchSize} completed`; document.querySelector('#learnerTitle').textContent=`${batch.year} practice`;
  for(const [index,question] of (batch.questions||[]).entries()){const card=document.createElement('article');card.className='question';card.id=`question-${index+1}`;const navButton=document.createElement('button');navButton.type='button';navButton.textContent=String(index+1);navButton.title=`Go to question ${index+1}`;navButton.onclick=()=>card.scrollIntoView({behavior:'smooth',block:'start'});questionNav.append(navButton);card.innerHTML=`<p>${escapeHtml(question.prompt)}</p><button class="secondary" type="button">Read question aloud</button><label>Your answer <input maxlength="200" inputmode="text"></label><button type="button">Save answer</button><p class="message" aria-live="polite"></p>`;const [read,input,save,feedback]=[card.querySelector('.secondary'),card.querySelector('input'),card.querySelector('button:not(.secondary)'),card.querySelector('.message')];read.onclick=()=>speak(question.prompt);save.onclick=async()=>{save.disabled=true;try{const result=(await call('submitProgressiveLearnerResponse')({learnerId,questionId:question.questionId,response:input.value})).data;feedback.textContent=result.feedback; if(result.batchComplete){nextBatch.classList.remove('hidden');} progress.textContent=`${batch.year} · Batch ${(batch.batchIndex||0)+1} · ${result.completed} of ${result.batchSize} completed`;}catch(error){feedback.textContent=error.message||'Your answer could not be saved. Try again.';save.disabled=false;}};questions.append(card);} if(!(batch.questions||[]).length&&completed===batch.batchSize)nextBatch.classList.remove('hidden');}
async function loadBatch(){message.textContent='Loading the protected practice group…'; const result=(await call('getProgressiveLearnerBatch')({learnerId})).data;batch=result;authCard.classList.add('hidden');learnerCard.classList.add('hidden');practiceCard.classList.remove('hidden');message.textContent='';render();}
async function showLearners(){const area=document.querySelector('#savedLearners');try{const {learners}=(await call('listProgressiveLearners')()).data;area.innerHTML=learners.length?`<p>Continue a saved learner:</p>${learners.map(item=>`<button type="button" data-id="${escapeHtml(item.learnerId)}">${escapeHtml(item.displayName)} · ${escapeHtml(item.year)}</button>`).join(' ')}`:'';area.querySelectorAll('button').forEach(button=>button.onclick=async()=>{learnerId=button.dataset.id;await loadBatch();});}catch{area.textContent='';}}
function dateLabel(value){return Number.isFinite(value)?new Intl.DateTimeFormat('en-GB',{dateStyle:'long'}).format(new Date(value)):'';}
async function refreshBillingStatus(){billingStatus.textContent='Checking your subscription…';manageSubscription.classList.add('hidden');try{const state=(await call('getParentBillingStatus')()).data;const until=dateLabel(state.currentPeriodEndMillis);if(state.status==='active')billingStatus.textContent=until?`Active · paid through ${until}`:'Active';else if(state.status==='cancels_at_period_end')billingStatus.textContent=until?`Cancels at the end of the paid period · access continues through ${until}`:'Cancels at the end of the paid period · access continues through your paid period';else billingStatus.textContent='Cancelled or expired · no active subscription';if(state.portalAvailable)manageSubscription.classList.remove('hidden');}catch{billingStatus.textContent='Subscription status is temporarily unavailable.';}}
onAuthStateChanged(auth,async user=>{if(user&&user.emailVerified){authCard.classList.add('hidden');learnerCard.classList.remove('hidden');billingCard.classList.remove('hidden');supportCard.classList.remove('hidden');message.textContent='Choose a child and study path to begin.';await Promise.all([showLearners(),refreshBillingStatus()]);}else if(user){billingCard.classList.add('hidden');supportCard.classList.add('hidden');message.textContent='Verify the parent email before accessing private learning.';}else{authCard.classList.remove('hidden');learnerCard.classList.add('hidden');billingCard.classList.add('hidden');supportCard.classList.add('hidden');practiceCard.classList.add('hidden');}});
document.querySelector('#signInForm').onsubmit=async event=>{event.preventDefault();try{await signInWithEmailAndPassword(auth,document.querySelector('#email').value.trim(),document.querySelector('#password').value);message.textContent='Checking your verified parent account…';}catch{message.textContent='We could not sign in with those details.';}};
document.querySelector('#resetPassword').onclick=async()=>{const email=document.querySelector('#email').value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){message.textContent='Enter your parent email address first.';return;}try{await sendPasswordResetEmail(auth,email);message.textContent='If that address has a BrightSum account, we have sent password-reset instructions.';}catch{message.textContent='We could not start password recovery. Please try again shortly.';}};
document.querySelector('#learnerForm').onsubmit=async event=>{event.preventDefault();try{const data=(await call('createProgressiveLearner')({displayName:document.querySelector('#displayName').value.trim(),year:document.querySelector('#year').value})).data;learnerId=data.learnerId;await loadBatch();}catch(error){message.textContent=error.message||'Private learning is available with an active BrightSum Practice subscription.';}};
supportForm.onsubmit=async event=>{event.preventDefault();const submit=supportForm.querySelector('button[type="submit"]'),category=document.querySelector('#supportCategory').value,request=document.querySelector('#supportRequest').value.trim();submit.disabled=true;supportStatus.textContent='Sending your support request…';try{const result=(await call('createSupportTicket')({category,message:request})).data;document.querySelector('#supportRequest').value='';supportStatus.textContent=result.reference?`Thanks. Your support reference is ${result.reference}. We have sent a confirmation to your verified parent email address.`:'Thanks. We have already received this support request.';}catch(error){supportStatus.textContent=error.message||'Your support request could not be sent. Please try again shortly.';}finally{submit.disabled=false;}};
manageSubscription.onclick=async()=>{manageSubscription.disabled=true;billingStatus.textContent='Opening secure billing management…';try{const result=(await call('createParentCustomerPortalSession')()).data;if(typeof result.url!=='string'||!result.url.startsWith('https://billing.stripe.com/'))throw new Error('Invalid billing portal address.');window.location.assign(result.url);}catch(error){billingStatus.textContent=error.message||'Billing management is temporarily unavailable.';manageSubscription.disabled=false;await refreshBillingStatus();}};
nextBatch.onclick=async()=>{try{await call('advanceProgressiveLearnerBatch')({learnerId});nextBatch.classList.add('hidden');await loadBatch();}catch(error){message.textContent=error.message||'Complete the current group before unlocking the next one.';}};
